# Generated by Django 5.0.3 on 2026-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews/')),
            ],
        ),
    ]
