# Generated by Django 5.0.3 on 2026-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='type',
            field=models.CharField(choices=[('2D', '2D Art'), ('3D', '3D Art'), ('ANIM', '2D Animation')], max_length=10),
        ),
    ]
