# Generated by Django 5.0.3 on 2026-04-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_artwork_options_artwork_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='type',
        ),
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='types',
            field=models.CharField(default='2D', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
