# Generated by Django 5.0.3 on 2026-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_artwork_type_artwork_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
