# Generated by Django 5.0.3 on 2026-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_artwork_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
