# Generated by Django 5.0.3 on 2026-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_artwork_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
